name: vysenet
description: "MVP Flutter to VyseNet network monitoring"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  provider: ^6.0.0
  http: 0.13.6
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  path: ^1.9.1
  sqflite: ^2.4.2
  crypto: ^3.0.6
  intl: ^0.20.2
  path_provider: ^2.1.5
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/